### ISSUE TITLE
Invalid testcase:  'omp ... for' construct with '{' following

### ISSUE THREAD

**Issue by tob2** [clang-ykt/omptests#2]
The following is invalid:

```C
#pragma omp for
  {
        for (int i = 0; i < N; i++) { ... }
  }
```
OpenMP does not permit the `{`...`}` structured block after the `pragma` line but the `for` has to follow directly.

See: https://www.openmp.org/spec-html/5.0/openmpsu41.html#x64-1290002.9.2

```C
#pragma omp for [clause[ [,] clause] ... ] new-line 
    for-loops
``` 
And I note that `{ ` is not a `for-loop`

Consequently, GCC Rejects this with: `error: for statement expected before '{' token`

There are several occurrences, e.g., `utilities/utilities.h` has:
```C
#define TESTD2(D, PRE, T, POST, V) { \
...
    _Pragma(D) \
     {T} \
``` 
which is called, e.g., by `t-reduction-struct/results/test.cpp`:
```C
#define REDUCTION_LOOP() \
    for (int i = 0; i < N; i++) { \
      REDUCTION_BODY(); \
    }
...
      TESTD2("omp target teams distribute parallel for num_teams(tms) thread_limit(ths) REDUCTION_MAP REDUCTION_CLAUSES",
        {
          REDUCTION_INIT();
        },
        REDUCTION_LOOP(),
...
```

**Comment by tob2** [comment]
Now FIXED :-) → Close.
Thanks @doru1004 for the reviews!

**Comment by doru1004** [comment]
> Now FIXED :-) → Close.
> Thanks @doru1004 for the reviews!

You're very welcome, thanks a lot for the contributions! :)
